---
title: "Case Study II"
author: "Quincy Roundtree"
date: "7/22/2018"
html_document:
keep_md: true
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
```

Bring in the data!

```{r data import , echo=TRUE}
attraw <- read_excel("~/Desktop/SMU Classes/MSDS 6306/Case Study II/CaseStudy2_2/CaseStudy2-data.xlsx")

View(attraw)
summary(attraw) # No NAs? 1470 lines of data No one under age 18 employee numbers go to 2068 but only 1470 lines. Job satisfaction mean 2.7 median 3.0 
```

## Start the EDA

Graphically look at the data

```{r inital EDA, echo=TRUE}
colnames(attraw)
ggplot(data = attraw) + geom_bar(mapping = aes(x = Age))
ggplot(data = attraw) + geom_bar(mapping = aes(x = Attrition, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = BusinessTravel, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = DailyRate), binwidth = 100)
ggplot(data = attraw) + geom_bar(mapping = aes(x = Department, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = DistanceFromHome))
ggplot(data = attraw) + geom_bar(mapping = aes(x = Education))
ggplot(data = attraw) + geom_bar(mapping = aes(x = EducationField, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = EmployeeCount))
ggplot(data = attraw) + geom_bar(mapping = aes(x = EmployeeNumber))
ggplot(data = attraw) + geom_bar(mapping = aes(x = EnvironmentSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = Gender,y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = HourlyRate))
ggplot(data = attraw) + geom_bar(mapping = aes(x = JobInvolvement, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = JobLevel, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = JobRole, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = JobSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = MaritalStatus, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = MonthlyIncome), binwidth = 5000)
ggplot(data = attraw) + geom_bar(mapping = aes(x = MonthlyRate), binwidth = 10000)
ggplot(data = attraw) + geom_bar(mapping = aes(x = NumCompaniesWorked))
ggplot(data = attraw) + geom_bar(mapping = aes(x = Over18))
ggplot(data = attraw) + geom_bar(mapping = aes(x = OverTime, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = PercentSalaryHike))
ggplot(data = attraw) + geom_bar(mapping = aes(x = PerformanceRating), binwidth = .5)
ggplot(data = attraw) + geom_bar(mapping = aes(x = RelationshipSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = StandardHours))
ggplot(data = attraw) + geom_bar(mapping = aes(x = StockOptionLevel))
ggplot(data = attraw) + geom_bar(mapping = aes(x = TotalWorkingYears))
ggplot(data = attraw) + geom_bar(mapping = aes(x = TrainingTimesLastYear))
ggplot(data = attraw) + geom_bar(mapping = aes(x = WorkLifeBalance, y = ..prop.., group = 1), stat = "count")
ggplot(data = attraw) + geom_bar(mapping = aes(x = YearsAtCompany))
ggplot(data = attraw) + geom_bar(mapping = aes(x = YearsInCurrentRole))
ggplot(data = attraw) + geom_bar(mapping = aes(x = YearsSinceLastPromotion))
ggplot(data = attraw) + geom_bar(mapping = aes(x = YearsWithCurrManager))
```

Graphically look at the data more

```{r inital EDA pt1, echo=TRUE}

ggplot(data = attraw) + geom_point(mapping = aes(x = EmployeeNumber, y = YearsAtCompany))

attryes <- subset(attraw, Attrition =="Yes", select=Age:YearsWithCurrManager)
attrno <- subset(attraw, Attrition =="No", select=Age:YearsWithCurrManager)

summary(attryes)
summary(attrno)

library(miscTools)

Mndat <- (colMeans(attraw[ , c("Age", "DailyRate", "DistanceFromHome",     "Education"        , "EnvironmentSatisfaction" , "HourlyRate",           "JobInvolvement"   ,        "JobLevel"      , "JobSatisfaction" ,  "MonthlyIncome",      "MonthlyRate" , "NumCompaniesWorked",  "PercentSalaryHike"   , "PerformanceRating"   ,     "RelationshipSatisfaction", "StockOptionLevel", "TotalWorkingYears"  ,      "TrainingTimesLastYear"  , "WorkLifeBalance"    ,     "YearsAtCompany"  , "YearsInCurrentRole"   ,  "YearsSinceLastPromotion" , "YearsWithCurrManager" )]))
Mnyes <- (colMeans(attryes[ , c("Age", "DailyRate", "DistanceFromHome",     "Education"        , "EnvironmentSatisfaction" , "HourlyRate",           "JobInvolvement"   ,        "JobLevel"      , "JobSatisfaction" ,  "MonthlyIncome",      "MonthlyRate" , "NumCompaniesWorked",  "PercentSalaryHike"   , "PerformanceRating"   ,     "RelationshipSatisfaction", "StockOptionLevel", "TotalWorkingYears"  ,      "TrainingTimesLastYear"  , "WorkLifeBalance"    ,     "YearsAtCompany"  , "YearsInCurrentRole"   ,  "YearsSinceLastPromotion" , "YearsWithCurrManager" )]))
Mnno <- (colMeans(attrno[ , c("Age", "DailyRate", "DistanceFromHome",     "Education"        , "EnvironmentSatisfaction" , "HourlyRate",           "JobInvolvement"   ,        "JobLevel"      , "JobSatisfaction" ,  "MonthlyIncome",      "MonthlyRate" , "NumCompaniesWorked",  "PercentSalaryHike"   , "PerformanceRating"   ,     "RelationshipSatisfaction", "StockOptionLevel", "TotalWorkingYears"  ,      "TrainingTimesLastYear"  , "WorkLifeBalance"    ,     "YearsAtCompany"  , "YearsInCurrentRole"   ,  "YearsSinceLastPromotion" , "YearsWithCurrManager" )]))

meandf <- data_frame(Mndat, Mnyes, Mnno)
tmeandf <- t(meandf)

Medat <- (colMedians(attraw[ ,c("Age", "DailyRate", "DistanceFromHome",     "Education"        , "EnvironmentSatisfaction" , "HourlyRate",           "JobInvolvement"   ,        "JobLevel"      , "JobSatisfaction" ,  "MonthlyIncome",      "MonthlyRate" , "NumCompaniesWorked",  "PercentSalaryHike"   , "PerformanceRating"   ,     "RelationshipSatisfaction", "StockOptionLevel", "TotalWorkingYears"  ,      "TrainingTimesLastYear"  , "WorkLifeBalance"    ,     "YearsAtCompany"  , "YearsInCurrentRole"   ,  "YearsSinceLastPromotion" , "YearsWithCurrManager" )]))

Meyes <- (colMedians(attryes[ ,c("Age", "DailyRate", "DistanceFromHome",     "Education"        , "EnvironmentSatisfaction" , "HourlyRate",           "JobInvolvement"   ,        "JobLevel"      , "JobSatisfaction" ,  "MonthlyIncome",      "MonthlyRate" , "NumCompaniesWorked",  "PercentSalaryHike"   , "PerformanceRating"   ,     "RelationshipSatisfaction", "StockOptionLevel", "TotalWorkingYears"  ,      "TrainingTimesLastYear"  , "WorkLifeBalance"    ,     "YearsAtCompany"  , "YearsInCurrentRole"   ,  "YearsSinceLastPromotion" , "YearsWithCurrManager" )]))

Meno <- (colMedians(attrno[ ,c("Age", "DailyRate", "DistanceFromHome",     "Education"        , "EnvironmentSatisfaction" , "HourlyRate",           "JobInvolvement"   ,        "JobLevel"      , "JobSatisfaction" ,  "MonthlyIncome",      "MonthlyRate" , "NumCompaniesWorked",  "PercentSalaryHike"   , "PerformanceRating"   ,     "RelationshipSatisfaction", "StockOptionLevel", "TotalWorkingYears"  ,      "TrainingTimesLastYear"  , "WorkLifeBalance"    ,     "YearsAtCompany"  , "YearsInCurrentRole"   ,  "YearsSinceLastPromotion" , "YearsWithCurrManager" )]))

meaddf <- data_frame(Medat, Meyes, Meno)

meandf1 <- add_column(meandf, Name = c("Age", "DailyRate", "DistanceFromHome",     "Education"        , "EnvironmentSatisfaction" , "HourlyRate",           "JobInvolvement"   ,        "JobLevel"      , "JobSatisfaction" ,  "MonthlyIncome",      "MonthlyRate" , "NumCompaniesWorked",  "PercentSalaryHike"   , "PerformanceRating"   ,     "RelationshipSatisfaction", "StockOptionLevel", "TotalWorkingYears"  ,      "TrainingTimesLastYear"  , "WorkLifeBalance"    ,     "YearsAtCompany"  , "YearsInCurrentRole"   ,  "YearsSinceLastPromotion" , "YearsWithCurrManager" ), .before = 1)

meaddf1 <- add_column(meaddf, Name = c("Age", "DailyRate", "DistanceFromHome",     "Education"        , "EnvironmentSatisfaction" , "HourlyRate",           "JobInvolvement"   ,        "JobLevel"      , "JobSatisfaction" ,  "MonthlyIncome",      "MonthlyRate" , "NumCompaniesWorked",  "PercentSalaryHike"   , "PerformanceRating"   ,     "RelationshipSatisfaction", "StockOptionLevel", "TotalWorkingYears"  ,      "TrainingTimesLastYear"  , "WorkLifeBalance"    ,     "YearsAtCompany"  , "YearsInCurrentRole"   ,  "YearsSinceLastPromotion" , "YearsWithCurrManager" ), .before = 1)

totaldf <- merge(meandf1, meaddf1, by="Name")
colnames(totaldf) <- c("FactorName", "Mean_original", "Mean_Yes", "Mean_No", "Median_original", "Median_Yes", "Median_No")

# Compare means of columns of the raw data vs noattrition vs yesattrition Items of note... Variables that seem to have little value. Employee number(doesnt seem to correlate to longer time with the company), Employee count(all =1), Standard hours(all = 80), Over 18 (all=Y). Signifigant variables needing more insight. Age mean for all=36.9 yes=33.6 Mean for no= 37.5 Median and mean close for all sets. DailyRate mean for all= 802 yes=750.36 Mean for no= 812 Median is lower by 50 in Yesattrition. Job level mean for all= 2.06 yes=1.63 Mean for no= 2.14 median for Yes is 1 much lower than others. Monthly Income mean for all=6502.93 yes=4787.93 Mean for no= 6832.74 about 1500 diffrence between all medians and means. Stock Optionlevel mean for all=.793 yes=527 Mean for no= .845 Median for all and No = 1 Yes is much lower with a median of 0. Total working years mean for all=11.27 yes=8.24 Mean for no= 11.86 Median and mean close for all sets. Years at company mean for all=7.00 yes=5.13 Mean for no= 7.36 Big jump of 40-60% from Median to Mean in all data sets. Years in current role mean for all=4.22 yes=2.90 Mean for no= 4.48 Jump of about 50% in all data sets. YearsSinceLast Promo mean for all= 2.18 yes=1.94 Mean for no= 2.23 Big jumps of 94 to 118% in all data sets. Years with curr Manager mean for all=4.12  yes=2.85 Mean for no= 4.36 Jumps about 40% between median to mean.Still need to look closer at categorical data.
```

Attrition only
```{r inital EDA pt2, echo=TRUE}

ggplot(data = attryes) + geom_bar(mapping = aes(x = Age))
ggplot(data = attryes) + geom_bar(mapping = aes(x = Attrition, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = BusinessTravel, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = DailyRate), binwidth = 100)
ggplot(data = attryes) + geom_bar(mapping = aes(x = Department, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = DistanceFromHome))
ggplot(data = attryes) + geom_bar(mapping = aes(x = Education))
ggplot(data = attryes) + geom_bar(mapping = aes(x = EducationField, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = EmployeeCount))
ggplot(data = attryes) + geom_bar(mapping = aes(x = EmployeeNumber))
ggplot(data = attryes) + geom_bar(mapping = aes(x = EnvironmentSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = Gender, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = HourlyRate))
ggplot(data = attryes) + geom_bar(mapping = aes(x = JobInvolvement, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = JobLevel, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = JobRole, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = JobSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = MaritalStatus, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = MonthlyIncome), binwidth = 5000)
ggplot(data = attryes) + geom_bar(mapping = aes(x = MonthlyRate), binwidth = 10000)
ggplot(data = attryes) + geom_bar(mapping = aes(x = NumCompaniesWorked))
ggplot(data = attryes) + geom_bar(mapping = aes(x = Over18))
ggplot(data = attryes) + geom_bar(mapping = aes(x = OverTime, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = PercentSalaryHike))
ggplot(data = attryes) + geom_bar(mapping = aes(x = PerformanceRating), binwidth = .5)
ggplot(data = attryes) + geom_bar(mapping = aes(x = RelationshipSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = StandardHours), binwidth = 1)
ggplot(data = attryes) + geom_bar(mapping = aes(x = StockOptionLevel))
ggplot(data = attryes) + geom_bar(mapping = aes(x = TotalWorkingYears))
ggplot(data = attryes) + geom_bar(mapping = aes(x = TrainingTimesLastYear))
ggplot(data = attryes) + geom_bar(mapping = aes(x = WorkLifeBalance, y = ..prop.., group = 1), stat = "count")
ggplot(data = attryes) + geom_bar(mapping = aes(x = YearsAtCompany))
ggplot(data = attryes) + geom_bar(mapping = aes(x = YearsInCurrentRole))
ggplot(data = attryes) + geom_bar(mapping = aes(x = YearsSinceLastPromotion))
ggplot(data = attryes) + geom_bar(mapping = aes(x = YearsWithCurrManager))

```

No attrition

```{r inital EDA pt3, echo=TRUE}

ggplot(data = attrno) + geom_bar(mapping = aes(x = Age))
ggplot(data = attrno) + geom_bar(mapping = aes(x = Attrition, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = BusinessTravel, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = DailyRate), binwidth = 100)
ggplot(data = attrno) + geom_bar(mapping = aes(x = Department, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = DistanceFromHome))
ggplot(data = attrno) + geom_bar(mapping = aes(x = Education))
ggplot(data = attrno) + geom_bar(mapping = aes(x = EducationField, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = EmployeeCount))
ggplot(data = attrno) + geom_bar(mapping = aes(x = EmployeeNumber))
ggplot(data = attrno) + geom_bar(mapping = aes(x = EnvironmentSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = Gender, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = HourlyRate))
ggplot(data = attrno) + geom_bar(mapping = aes(x = JobInvolvement, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = JobLevel, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = JobRole, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = JobSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = MaritalStatus, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = MonthlyIncome), binwidth = 5000)
ggplot(data = attrno) + geom_bar(mapping = aes(x = MonthlyRate), binwidth = 10000)
ggplot(data = attrno) + geom_bar(mapping = aes(x = NumCompaniesWorked))
ggplot(data = attrno) + geom_bar(mapping = aes(x = Over18))
ggplot(data = attrno) + geom_bar(mapping = aes(x = OverTime, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = PercentSalaryHike))
ggplot(data = attrno) + geom_bar(mapping = aes(x = PerformanceRating), binwidth = .5)
ggplot(data = attrno) + geom_bar(mapping = aes(x = RelationshipSatisfaction, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = StandardHours))
ggplot(data = attrno) + geom_bar(mapping = aes(x = StockOptionLevel))
ggplot(data = attrno) + geom_bar(mapping = aes(x = TotalWorkingYears))
ggplot(data = attrno) + geom_bar(mapping = aes(x = TrainingTimesLastYear))
ggplot(data = attrno) + geom_bar(mapping = aes(x = WorkLifeBalance, y = ..prop.., group = 1), stat = "count")
ggplot(data = attrno) + geom_bar(mapping = aes(x = YearsAtCompany))
ggplot(data = attrno) + geom_bar(mapping = aes(x = YearsInCurrentRole))
ggplot(data = attrno) + geom_bar(mapping = aes(x = YearsSinceLastPromotion))
ggplot(data = attrno) + geom_bar(mapping = aes(x = YearsWithCurrManager))

```

```{r inital EDA part4, echo=TRUE}

ggplot(data = attraw, mapping = aes(x = Age, y = MonthlyIncome)) + geom_point()
ggplot(data = attraw, mapping = aes(x = DailyRate, y = DistanceFromHome )) + geom_point()
ggplot(data = attraw, mapping = aes(x = YearsAtCompany, y = HourlyRate )) + geom_point()
ggplot(data = attraw, mapping = aes(x = NumCompaniesWorked, y = MonthlyIncome )) + geom_point()
ggplot(data = attraw, mapping = aes(x = TotalWorkingYears, y = PercentSalaryHike)) + geom_point()
ggplot(data = attraw, mapping = aes(x = YearsAtCompany, y = MonthlyIncome )) + geom_point()
ggplot(data = attraw, mapping = aes(x = YearsAtCompany, y = YearsSinceLastPromotion )) + geom_point()
ggplot(data = attraw, mapping = aes(x = DailyRate, y = MonthlyRate)) + geom_point()
ggplot(data = attraw, mapping = aes(x = Age, y = YearsSinceLastPromotion)) + geom_point()
ggplot(data = attraw, mapping = aes(x = StockOptionLevel, y = YearsSinceLastPromotion)) + geom_point()
ggplot(data = attraw, mapping = aes(x = Age, y = TotalWorkingYears)) + geom_point()
ggplot(data = attraw, mapping = aes(x = YearsInCurrentRole, y = MonthlyIncome)) + geom_point()
ggplot(data = attraw, mapping = aes(x = YearsSinceLastPromotion, y = YearsWithCurrManager)) + geom_point()

```
Multiple regression

```{r inital EDA part5, echo=TRUE}
# just for kicks
attrnewy <- attryes
attrnewn <- attrno
attrnewr <- attraw

attcoly <- ifelse(attrnewy$Attrition == "Yes", "1", NA)
attcoln <- ifelse(attrnewn$Attrition == "No", "1", NA)
attcolr<- ifelse(attrnewr$Attrition == "Yes", "1", "0")

attrnewy$Attrition <- attcoly
attrnewn$Attrition <- attcoln
attrnewr$Attrition <- attcolr


lm(formula = Attrition ~ Age + DailyRate + DistanceFromHome+ Education + EnvironmentSatisfaction + HourlyRate + JobInvolvement + JobLevel + JobSatisfaction + MonthlyIncome + MonthlyRate + NumCompaniesWorked + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, data = attrnewy )

lm(formula = Attrition ~ Age + DailyRate + DistanceFromHome+ Education + EnvironmentSatisfaction + HourlyRate + JobInvolvement + JobLevel + JobSatisfaction + MonthlyIncome + MonthlyRate + NumCompaniesWorked + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, data = attrnewn )

lm(formula = Attrition ~ Age + DailyRate + DistanceFromHome+ Education + EnvironmentSatisfaction + HourlyRate + JobInvolvement + JobLevel + JobSatisfaction + MonthlyIncome + MonthlyRate + NumCompaniesWorked + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, data = attrnewr )
# Need to narrow down variables to check correlation


```
